export const cropsData = [
  // ===== VEGETABLES (75) =====
  {
    name: 'Asparagus',
    category: 'vegetables',
    rowSpacing: '36-48',
    plantSpacing: '12-18',
    soilPh: '6.5-7.5',
    daysToMaturity: 365,
    plantingDepth: '6-8',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Asparagus beetles, Japanese beetles',
    commonDiseases: 'Rust, Fusarium wilt',
    fertilizerSchedule: 'Monthly with balanced fertilizer, heavy feeding in spring',
    harvestTips: 'Harvest spears when 6-8 inches tall, cut below soil surface',
  },
  {
    name: 'Artichoke',
    category: 'vegetables',
    rowSpacing: '36-48',
    plantSpacing: '24-36',
    soilPh: '6.0-7.5',
    daysToMaturity: 90,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Aphids, thistle caterpillars',
    commonDiseases: 'Leaf spot, root rot',
    fertilizerSchedule: 'Every 4-6 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Cut heads before buds open, harvest in morning',
  },
  {
    name: 'Arugula',
    category: 'vegetables',
    rowSpacing: '6-12',
    plantSpacing: '3-6',
    soilPh: '6.0-7.0',
    daysToMaturity: 30,
    plantingDepth: '1/4',
    sunRequirement: 'Partial Shade (4-6 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Flea beetles, slugs',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest leaves when young and tender, before flowering',
  },
  {
    name: 'Beet',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '2-3',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1/2-1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Leaf miners, beet armyworms',
    commonDiseases: 'Cercospora leaf spot, root rot',
    fertilizerSchedule: 'Monthly with balanced fertilizer',
    harvestTips: 'Pull when 1-3 inches in diameter for best quality',
  },
  {
    name: 'Bok Choy',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 45,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Downy mildew, black rot',
    fertilizerSchedule: 'Every 2-3 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest outer leaves or entire head when 5-8 inches tall',
  },
  {
    name: 'Broccoli',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '18-24',
    soilPh: '6.0-7.0',
    daysToMaturity: 70,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage loopers, flea beetles',
    commonDiseases: 'Downy mildew, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Cut central head when tight and green, side shoots appear later',
  },
  {
    name: 'Brussels Sprouts',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '18-24',
    soilPh: '6.0-7.5',
    daysToMaturity: 90,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage worms, whiteflies',
    commonDiseases: 'Powdery mildew, clubroot',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest from bottom up when 1-1.5 inches in diameter',
  },
  {
    name: 'Cabbage',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '12-18',
    soilPh: '6.0-7.5',
    daysToMaturity: 70,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Cabbage moths, imported cabbage worms',
    commonDiseases: 'Black rot, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when heads feel firm, cut at base with sharp knife',
  },
  {
    name: 'Cauliflower',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '18-24',
    soilPh: '6.0-7.0',
    daysToMaturity: 70,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Clubroot, leaf spot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Cut when head is tight and white, before curds separate',
  },
  {
    name: 'Celery',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-8',
    soilPh: '6.0-7.0',
    daysToMaturity: 120,
    plantingDepth: 'Surface',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'High',
    commonPests: 'Celery leaf tier, carrot rust fly',
    commonDiseases: 'Early blight, pink rot',
    fertilizerSchedule: 'Every 2-3 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest outer stalks when 10-12 inches tall, cut at base',
  },
  {
    name: 'Chard',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 50,
    plantingDepth: '1/2-1',
    sunRequirement: 'Full Sun to Partial Shade',
    waterRequirement: 'Moderate',
    commonPests: 'Leaf miners, slugs',
    commonDiseases: 'Leaf spot, powdery mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest outer leaves regularly to promote growth',
  },
  {
    name: 'Collard Greens',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '12-18',
    soilPh: '6.0-7.5',
    daysToMaturity: 60,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Cabbage moths, harlequin bugs',
    commonDiseases: 'Clubroot, black rot',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest outer leaves when 10-12 inches long',
  },
  {
    name: 'Corn',
    category: 'vegetables',
    rowSpacing: '30-36',
    plantSpacing: '8-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 70,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Corn borers, armyworms, earwigs',
    commonDiseases: 'Northern leaf blight, rust',
    fertilizerSchedule: 'Side-dress with nitrogen at V4-V6 stage and tasseling',
    harvestTips: 'Pick when kernels are full and milky, silk begins to brown',
  },
  {
    name: 'Cucumber',
    category: 'vegetables',
    rowSpacing: '36-48',
    plantSpacing: '12-18',
    soilPh: '6.0-7.0',
    daysToMaturity: 50,
    plantingDepth: '1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Spider mites, squash beetles',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when 6-8 inches long, before yellowing',
  },
  {
    name: 'Eggplant',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '18-24',
    soilPh: '6.0-6.8',
    daysToMaturity: 75,
    plantingDepth: '1/8-1/4',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Flea beetles, spider mites',
    commonDiseases: 'Early blight, fusarium wilt',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Cut when glossy and firm, before color dulls',
  },
  {
    name: 'Endive',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '8-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Slugs, aphids',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Blanch before harvest by covering with light-blocking material',
  },
  {
    name: 'Garlic',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '4-6',
    soilPh: '6.0-7.0',
    daysToMaturity: 240,
    plantingDepth: '2-3',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Low to Moderate',
    commonPests: 'Onion flies, thrips',
    commonDiseases: 'White rot, fusarium rot',
    fertilizerSchedule: 'Fall planting with compost, spring nitrogen feeding',
    harvestTips: 'Harvest when tops fall over and dry, cure in shade 3-4 weeks',
  },
  {
    name: 'Green Beans',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '3-4',
    soilPh: '6.0-7.0',
    daysToMaturity: 50,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Mexican bean beetles, spider mites',
    commonDiseases: 'Bean rust, powdery mildew',
    fertilizerSchedule: 'Monthly with balanced fertilizer',
    harvestTips: 'Harvest when pods snap easily, before seeds bulge',
  },
  {
    name: 'Kale',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '12-18',
    soilPh: '6.0-7.5',
    daysToMaturity: 55,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Cabbage moths, harlequin bugs',
    commonDiseases: 'Clubroot, powdery mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest outer leaves, flavor improves after light frost',
  },
  {
    name: 'Kohlrabi',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '4-6',
    soilPh: '6.0-7.5',
    daysToMaturity: 45,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Clubroot, black rot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when 2-3 inches diameter, becomes woody if larger',
  },
  {
    name: 'Leek',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '4-6',
    soilPh: '6.0-7.0',
    daysToMaturity: 150,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Onion flies, thrips',
    commonDiseases: 'White rot, pink root',
    fertilizerSchedule: 'Every 4-6 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest when white section is 1-2 inches thick',
  },
  {
    name: 'Okra',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '12-18',
    soilPh: '6.0-6.8',
    daysToMaturity: 50,
    plantingDepth: '1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Japanese beetles, spider mites',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when 3-4 inches long, becomes tough if larger',
  },
  {
    name: 'Onion',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '2-4',
    soilPh: '6.0-7.0',
    daysToMaturity: 120,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Onion flies, thrips',
    commonDiseases: 'Pink root, fusarium rot',
    fertilizerSchedule: 'Monthly with nitrogen-rich fertilizer',
    harvestTips: 'Harvest when tops fall over, cure in warm, dry place 4-6 weeks',
  },
  {
    name: 'Parsnip',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '2-3',
    soilPh: '6.0-7.0',
    daysToMaturity: 120,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Carrot rust fly, webworms',
    commonDiseases: 'Leaf blotch, root rot',
    fertilizerSchedule: 'Monthly with balanced fertilizer',
    harvestTips: 'Harvest after frost for improved sweetness',
  },
  {
    name: 'Peas',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '2-3',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Pea moths, seed corn maggots',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Light feeding, or use inoculant for nitrogen fixation',
    harvestTips: 'Pick when pods are full but still tender and sweet',
  },
  {
    name: 'Pepper (Bell)',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '18-24',
    soilPh: '6.0-6.8',
    daysToMaturity: 90,
    plantingDepth: '1/8-1/4',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Spider mites, whiteflies',
    commonDiseases: 'Bacterial spot, anthracnose',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest at green stage or wait for color change',
  },
  {
    name: 'Pepper (Hot)',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '18-24',
    soilPh: '6.0-6.8',
    daysToMaturity: 90,
    plantingDepth: '1/8-1/4',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Spider mites, whiteflies',
    commonDiseases: 'Bacterial spot, phytophthora',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when fully mature for maximum heat level',
  },
  {
    name: 'Potato',
    category: 'vegetables',
    rowSpacing: '30-36',
    plantSpacing: '12-15',
    soilPh: '5.0-6.5',
    daysToMaturity: 90,
    plantingDepth: '4-6',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Colorado potato beetles, flea beetles',
    commonDiseases: 'Late blight, early blight',
    fertilizerSchedule: 'Monthly with balanced or nitrogen-rich fertilizer',
    harvestTips: 'Harvest when vines die back, cure in cool dark place 1-2 weeks',
  },
  {
    name: 'Pumpkin',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '24-36',
    soilPh: '6.0-6.8',
    daysToMaturity: 120,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when rind is hard and stems dry, before frost',
  },
  {
    name: 'Radish',
    category: 'vegetables',
    rowSpacing: '6-12',
    plantSpacing: '1-2',
    soilPh: '6.0-7.0',
    daysToMaturity: 25,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Flea beetles, cabbage root fly',
    commonDiseases: 'Clubroot, root rot',
    fertilizerSchedule: 'Light feeding or none needed',
    harvestTips: 'Harvest at 1/2-1 inch diameter for best quality',
  },
  {
    name: 'Rutabaga',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '3-6',
    soilPh: '6.0-7.0',
    daysToMaturity: 90,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Flea beetles, root maggots',
    commonDiseases: 'Clubroot, powdery mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest after light frost for improved flavor',
  },
  {
    name: 'Shallot',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-8',
    soilPh: '6.0-7.0',
    daysToMaturity: 120,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Onion flies, thrips',
    commonDiseases: 'White rot, fusarium rot',
    fertilizerSchedule: 'Fall planting with compost, spring nitrogen feeding',
    harvestTips: 'Harvest when tops fall over, cure like onions',
  },
  {
    name: 'Spinach',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '3-6',
    soilPh: '6.5-7.0',
    daysToMaturity: 40,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun to Partial Shade',
    waterRequirement: 'Moderate to High',
    commonPests: 'Leaf miners, slugs',
    commonDiseases: 'Downy mildew, white rust',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest outer leaves or pull entire plant when 6-8 inches tall',
  },
  {
    name: 'Squash (Summer)',
    category: 'vegetables',
    rowSpacing: '48-60',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 50,
    plantingDepth: '1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when 6-8 inches long, frequent picking encourages production',
  },
  {
    name: 'Squash (Winter)',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 100,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when rind hardens, before frost',
  },
  {
    name: 'Sweet Potato',
    category: 'vegetables',
    rowSpacing: '36-48',
    plantSpacing: '12-18',
    soilPh: '5.8-6.2',
    daysToMaturity: 150,
    plantingDepth: 'Slips planted 2-3 inches deep',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Sweet potato whitefly, flea beetles',
    commonDiseases: 'Fusarium wilt, leaf spot',
    fertilizerSchedule: 'Monthly with balanced or potassium-rich fertilizer',
    harvestTips: 'Harvest before frost, cure at 80-85°F for 1-2 weeks',
  },
  {
    name: 'Tomatillo',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 70,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Tomato worms, flea beetles',
    commonDiseases: 'Early blight, powdery mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when fruit fills husk and color changes',
  },
  {
    name: 'Tomato',
    category: 'vegetables',
    rowSpacing: '36-48',
    plantSpacing: '24-36',
    soilPh: '6.0-6.8',
    daysToMaturity: 70,
    plantingDepth: '1/8-1/4',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Tomato hornworms, whiteflies',
    commonDiseases: 'Early blight, late blight, septoria leaf spot',
    fertilizerSchedule: 'Every 2-3 weeks with balanced fertilizer',
    harvestTips: 'Pick when fully colored but still slightly soft',
  },
  {
    name: 'Turnip',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '2-4',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Flea beetles, cabbage root fly',
    commonDiseases: 'Clubroot, root rot',
    fertilizerSchedule: 'Monthly with balanced fertilizer',
    harvestTips: 'Harvest when 2-3 inches diameter, greens edible too',
  },
  {
    name: 'Zucchini',
    category: 'vegetables',
    rowSpacing: '48-60',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 50,
    plantingDepth: '1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest at 6-8 inches long for tender texture',
  },
  {
    name: 'Watercress',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.5-7.5',
    daysToMaturity: 30,
    plantingDepth: '1/4',
    sunRequirement: 'Partial Shade (4-6 hours)',
    waterRequirement: 'High',
    commonPests: 'Leaf beetles, slugs',
    commonDiseases: 'Downy mildew, powdery mildew',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest outer leaves when 3-4 inches long',
  },
  {
    name: 'Radicchio',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '8-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 75,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Slugs, flea beetles',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Blanch before harvest for milder flavor',
  },
  {
    name: 'Fennel (Bulb)',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-9',
    soilPh: '6.0-7.0',
    daysToMaturity: 90,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Parsley worms, slugs',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when bulb is 3-4 inches diameter',
  },
  {
    name: 'Celeriac',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-8',
    soilPh: '6.0-7.0',
    daysToMaturity: 120,
    plantingDepth: 'Surface',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Celery leaf tier, carrot rust fly',
    commonDiseases: 'Early blight, pink rot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when 3-4 inches diameter, roots edible',
  },
  {
    name: 'Jicama',
    category: 'vegetables',
    rowSpacing: '36-48',
    plantSpacing: '12-18',
    soilPh: '6.0-7.0',
    daysToMaturity: 180,
    plantingDepth: '1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Bean beetles, aphids',
    commonDiseases: 'Root rot, leaf spot',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest tubers when 2-3 lbs, before first frost',
  },
  {
    name: 'Horseradish',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '18-24',
    soilPh: '5.5-7.0',
    daysToMaturity: 180,
    plantingDepth: '2-3',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Flea beetles, slugs',
    commonDiseases: 'Leaf spot, root rot',
    fertilizerSchedule: 'Spring with compost, monthly balanced fertilizer',
    harvestTips: 'Harvest in fall when flavor peaks, after frost',
  },
  {
    name: 'Salsify',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '2-3',
    soilPh: '6.0-7.0',
    daysToMaturity: 150,
    plantingDepth: '1/2-1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Carrot rust fly, webworms',
    commonDiseases: 'Leaf blotch, root rot',
    fertilizerSchedule: 'Monthly with balanced fertilizer',
    harvestTips: 'Harvest after frost for improved sweetness',
  },
  {
    name: 'Chicory',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-9',
    soilPh: '6.0-7.0',
    daysToMaturity: 120,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Slugs, aphids',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Blanch and force for chicories, or harvest greens raw',
  },
  {
    name: 'Mustard Greens',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.0-7.5',
    daysToMaturity: 45,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Downy mildew, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest outer leaves regularly, flavor better in cool weather',
  },
  {
    name: 'Mizuna',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 30,
    plantingDepth: '1/4',
    sunRequirement: 'Full Sun to Partial Shade',
    waterRequirement: 'Moderate',
    commonPests: 'Flea beetles, slugs',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 2-3 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest young leaves for tender texture',
  },
  {
    name: 'Tatsoi',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 45,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun to Partial Shade',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Downy mildew, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest entire rosette or outer leaves',
  },
  {
    name: 'Napa Cabbage',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '12-18',
    soilPh: '6.0-7.5',
    daysToMaturity: 70,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, imported cabbage worms',
    commonDiseases: 'Black rot, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest when head is firm and 10-12 inches tall',
  },
  {
    name: 'Savoy Cabbage',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '12-18',
    soilPh: '6.0-7.5',
    daysToMaturity: 75,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Cabbage moths, imported cabbage worms',
    commonDiseases: 'Black rot, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when head is firm, wrinkled leaves are characteristic',
  },
  {
    name: 'Red Cabbage',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '12-18',
    soilPh: '6.0-7.5',
    daysToMaturity: 80,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Cabbage moths, imported cabbage worms',
    commonDiseases: 'Black rot, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when firm, provide shade to maintain red color',
  },
  {
    name: 'Romanesco',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '18-24',
    soilPh: '6.0-7.0',
    daysToMaturity: 75,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Clubroot, leaf spot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Cut central head when tight, similar to broccoli',
  },
  {
    name: 'Broccolini',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '18-24',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Downy mildew, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest tender shoots when 4-6 inches long',
  },
  {
    name: 'Chinese Broccoli',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '12-18',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Downy mildew, clubroot',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest when flower buds are tight and small',
  },
  {
    name: 'Rapini',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 50,
    plantingDepth: '1/4-1/2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Cabbage moths, flea beetles',
    commonDiseases: 'Clubroot, powdery mildew',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest before flowers open, side shoots grow after main cut',
  },
  {
    name: 'Fava Beans',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '4-6',
    soilPh: '6.0-7.0',
    daysToMaturity: 80,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Pea moths, seed corn maggots',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Light feeding, nitrogen fixation from nodules',
    harvestTips: 'Harvest pods when 3-4 inches long and still tender',
  },
  {
    name: 'Lima Beans',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '4-6',
    soilPh: '6.0-7.0',
    daysToMaturity: 85,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Mexican bean beetles, spider mites',
    commonDiseases: 'Bean rust, powdery mildew',
    fertilizerSchedule: 'Light feeding or use inoculant for nitrogen fixation',
    harvestTips: 'Harvest pods when full but still green, or let dry on vine',
  },
  {
    name: 'Edamame',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '3-4',
    soilPh: '6.0-7.0',
    daysToMaturity: 65,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Japanese beetles, spider mites',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Light feeding or use inoculant for nitrogen fixation',
    harvestTips: 'Harvest when pods are full and bright green',
  },
  {
    name: 'Yard Long Beans',
    category: 'vegetables',
    rowSpacing: '24-36',
    plantSpacing: '4-6',
    soilPh: '6.0-7.0',
    daysToMaturity: 75,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Bean beetles, spider mites',
    commonDiseases: 'Powdery mildew, rust',
    fertilizerSchedule: 'Light feeding or use inoculant for nitrogen fixation',
    harvestTips: 'Harvest when 12-15 inches long and tender',
  },
  {
    name: 'Wax Beans',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '3-4',
    soilPh: '6.0-7.0',
    daysToMaturity: 50,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Mexican bean beetles, spider mites',
    commonDiseases: 'Bean rust, powdery mildew',
    fertilizerSchedule: 'Light feeding or use inoculant for nitrogen fixation',
    harvestTips: 'Harvest when 5-6 inches long and still tender',
  },
  {
    name: 'Snap Peas',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '2-3',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Pea moths, seed corn maggots',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Light feeding or use inoculant for nitrogen fixation',
    harvestTips: 'Harvest when pods are plump but still tender and sweet',
  },
  {
    name: 'Snow Peas',
    category: 'vegetables',
    rowSpacing: '18-24',
    plantSpacing: '2-3',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Pea moths, seed corn maggots',
    commonDiseases: 'Powdery mildew, root rot',
    fertilizerSchedule: 'Light feeding or use inoculant for nitrogen fixation',
    harvestTips: 'Harvest when pods are still flat and tender',
  },
  {
    name: 'Butternut Squash',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 110,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when tan and hard, before frost',
  },
  {
    name: 'Acorn Squash',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 90,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when dark green and hard, stem browns',
  },
  {
    name: 'Spaghetti Squash',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 90,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when yellow and hard to the touch',
  },
  {
    name: 'Delicata Squash',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 90,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when cream colored with green stripes',
  },
  {
    name: 'Hubbard Squash',
    category: 'vegetables',
    rowSpacing: '96-120',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 110,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when hard and color deepens, before frost',
  },
  {
    name: 'Kabocha Squash',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 110,
    plantingDepth: '1-2',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when dark green and stem browns',
  },
  {
    name: 'Patty Pan Squash',
    category: 'vegetables',
    rowSpacing: '48-60',
    plantSpacing: '24-36',
    soilPh: '6.0-7.0',
    daysToMaturity: 60,
    plantingDepth: '1',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate to High',
    commonPests: 'Squash bugs, squash vine borers',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 3-4 weeks with balanced fertilizer',
    harvestTips: 'Harvest when 3-4 inches diameter and tender',
  },
  {
    name: 'Chayote',
    category: 'vegetables',
    rowSpacing: '72-96',
    plantSpacing: '36-48',
    soilPh: '6.0-7.0',
    daysToMaturity: 150,
    plantingDepth: '3-4',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Leaf miners, aphids',
    commonDiseases: 'Root rot, leaf spot',
    fertilizerSchedule: 'Every 4-6 weeks with balanced fertilizer',
    harvestTips: 'Harvest when 3-4 inches long and tender',
  },
  {
    name: 'Lettuce',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '6-12',
    soilPh: '6.0-7.0',
    daysToMaturity: 45,
    plantingDepth: '1/4',
    sunRequirement: 'Partial Shade (4-6 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Slugs, aphids, leaf miners',
    commonDiseases: 'Powdery mildew, downy mildew',
    fertilizerSchedule: 'Every 3-4 weeks with nitrogen-rich fertilizer',
    harvestTips: 'Harvest outer leaves regularly or cut entire head',
  },
  {
    name: 'Carrot',
    category: 'vegetables',
    rowSpacing: '12-18',
    plantSpacing: '2-3',
    soilPh: '6.0-6.8',
    daysToMaturity: 70,
    plantingDepth: '1/4',
    sunRequirement: 'Full Sun (6-8 hours)',
    waterRequirement: 'Moderate',
    commonPests: 'Rust flies, carrot weevils',
    commonDiseases: 'Cavity spot, cercospora leaf spot',
    fertilizerSchedule: 'Monthly with balanced fertilizer',
    harvestTips: 'Pull when shoulders are 1/2 inch diameter',
  },
];
